# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-04 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0010_auto_20170304_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbook',
            name='duration',
        ),
    ]
