# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-04 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0012_auto_20170304_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='duration',
            field=models.CharField(choices=[('hour', 'hour'), ('day', 'day'), ('week', 'week')], default='hour', max_length=4),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='playbook_path',
            field=models.FilePathField(default='test.yml', match='*.yml', max_length=200, path='D:\\segev'),
        ),
    ]
