# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-04 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0013_auto_20170305_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook',
            name='playbook_path',
            field=models.FilePathField(match='*.yml', max_length=200, path='D:\\segev'),
        ),
    ]
