# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-05 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0015_remove_playbook_playbook_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='playbook_name',
            field=models.CharField(default='noName.yml', max_length=100),
        ),
    ]
