# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-05 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0016_playbook_playbook_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbook',
            name='playbook_name',
        ),
        migrations.AddField(
            model_name='playbook',
            name='playbook_text',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
