# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-05 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0017_auto_20170305_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='playbook_description',
            field=models.CharField(default='No description', max_length=10000),
        ),
    ]
